# Generated by Django 3.1.3 on 2021-08-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
